Dev jannik
gz-bad-erzland-p2/NextJS-Office-Sharing pull request #11
Opened 2022-12-13 09:43 UTC by JannikHein

2022-12-13 15:48 UTC, derech1e requested changes
Build Fehler bitte beheben

2022-12-13 15:48 UTC, derech1e commented on components/wizard/page/TimeSlotSelectorComponent.tsx
> +                                <label for="countries" className="w-full block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select an option</label>
Hier tritt noch ein Build Fehler auf. Bitte überprüfen!

2022-12-15 07:00 UTC, JannikHein commented on components/wizard/page/TimeSlotSelectorComponent.tsx
> +                                <label for="countries" className="w-full block mb-2 text-sm font-medium text-gray-900 dark:text-white">Select an option</label>
wurde behoben

2022-12-15 07:04 UTC, derech1e approved these changes

2022-12-15 07:05 UTC, merged